class Foods{
  public static void main(String[] hotel){
  String[] foods={"chicken biriyani","roti","chapati","pasta","pizza","burger","rice","egg","daal","pulav","kabab","puri","dosa","idli","vada","fish","berries","soyabean","salad","cereals","soup","dairy","cheese","broccoli","oatmeal","watermelon","chips","icecream","soda","fries","oreo","puff","cake","biscuit","chocolate","vadapav","apple","mango","tomato","potato","chickentikka","chickenkurma","chickensalad","fishcury","eggcury","bannana",
  "orange","pineapple","grape","lemon","cherry","apricot","pear","guava","papaya","peach","fig","plum","blueberry","jackfruit","coconut","kiwi","muskmelon","pits","core","melons"};
    System.out.println("food="+foods[0]);
  System.out.println("food="+foods[1]);
  System.out.println("food="+foods[2]);
  System.out.println("food="+foods[3]);
  System.out.println("food="+foods[4]);
  System.out.println("food="+foods[6]);
  System.out.println("food="+foods[7]);
  System.out.println("food="+foods[8]);
  System.out.println("food="+foods[9]);
  System.out.println("food="+foods[10]);
  System.out.println("food="+foods[11]);
  System.out.println("food="+foods[12]);
  System.out.println("food="+foods[13]);
  System.out.println("food="+foods[14]);
  System.out.println("food="+foods[15]);
  System.out.println("food="+foods[16]);
  System.out.println("food="+foods[17]);
  System.out.println("food="+foods[18]);
  System.out.println("food="+foods[19]);
  System.out.println("food="+foods[20]);
  System.out.println("food="+foods[21]);
  System.out.println("food="+foods[22]);
  System.out.println("food="+foods[23]);
  System.out.println("food="+foods[24]);
  System.out.println("food="+foods[25]);
  System.out.println("food="+foods[26]);
  System.out.println("food="+foods[27]);
  System.out.println("food="+foods[28]);
  System.out.println("food="+foods[29]);
  System.out.println("food="+foods[30]);
  System.out.println("food="+foods[31]);  
  System.out.println("food="+foods[31]); 
  System.out.println("food="+foods[32]);
  System.out.println("food="+foods[33]);
  System.out.println("food="+foods[34]);
  System.out.println("food="+foods[35]);
  System.out.println("food="+foods[36]);
  System.out.println("food="+foods[37]);
  System.out.println("food="+foods[38]);
  System.out.println("food="+foods[39]);
  System.out.println("food="+foods[40]); 
  System.out.println("food="+foods[41]);
  System.out.println("food="+foods[42]);
  System.out.println("food="+foods[43]);
  System.out.println("food="+foods[44]);
  System.out.println("food="+foods[45]);
  System.out.println("food="+foods[46]);
  System.out.println("food="+foods[47]);
  System.out.println("food="+foods[48]);
  System.out.println("food="+foods[49]);
  System.out.println("food="+foods[50]);
  System.out.println("food="+foods[51]);
  System.out.println("food="+foods[42]);
  System.out.println("food="+foods[53]);
  System.out.println("food="+foods[54]);
  System.out.println("food="+foods[55]);
  System.out.println("food="+foods[56]);
  System.out.println("food="+foods[57]);
  System.out.println("food="+foods[58]);
  System.out.println("food="+foods[59]);
  System.out.println("food="+foods[60]);
  System.out.println("food="+foods[61]);
  System.out.println("food="+foods[62]);
  System.out.println("food="+foods[63]);
  System.out.println("food="+foods[64]);
  System.out.println("food="+foods[65]);
  //System.out.println("food="+foods[66);
  }
  
  
}